# -*- coding: utf-8 -*-
import os
import csv
import psycopg2
from config import DB_CONFIG, OUTPUT_DIR


def importar_datos():
    print("=== INICIANDO IMPORTACIÓN AUTOMÁTICA EN POSTGRESQL ===")

    try:
        conn = psycopg2.connect(**DB_CONFIG)
    except UnicodeDecodeError:
        conn_str = f"dbname='{DB_CONFIG['dbname']}' user='{DB_CONFIG['user']}' password='{DB_CONFIG['password']}' host='{DB_CONFIG['host']}' port={DB_CONFIG['port']}"
        conn = psycopg2.connect(conn_str.encode("utf-8"))

    cursor = conn.cursor()

    tablas = [
        ("banco_security", "usuario_interno"),
        ("banco_core", "cliente"),
        ("banco_core", "persona_natural"),
        ("banco_core", "persona_juridica"),
        ("banco_core", "cliente_contacto"),
        ("banco_core", "cuenta"),
        ("banco_core", "cuenta_titular"),
        ("banco_core", "evento_cuenta"),
        ("banco_core", "transaccion"),
        ("banco_core", "asiento_contable"),
    ]

    for esquema, tabla in tablas:
        ruta_csv = os.path.join(OUTPUT_DIR, f"{tabla}.csv")

        if not os.path.exists(ruta_csv):
            print(f"  [!] Archivo no encontrado: {ruta_csv}")
            continue

        print(f"Cargando {esquema}.{tabla}...")

        # 1. Vaciar la tabla previa en cascada
        cursor.execute(f"TRUNCATE TABLE {esquema}.{tabla} CASCADE;")

        # 2. Permitir inserción explícita en columnas autoincrementales
        cursor.execute(
            f"""
            DO $$
            BEGIN
                EXECUTE (
                    SELECT 'ALTER TABLE ' || table_schema || '.' || table_name || 
                           ' ALTER COLUMN ' || column_name || ' SET GENERATED BY DEFAULT'
                    FROM information_schema.columns
                    WHERE table_schema = '{esquema}' 
                      AND table_name = '{tabla}' 
                      AND is_identity = 'YES'
                    LIMIT 1
                );
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END $$;
        """
        )

        # 3. Leer encabezados del CSV para mapear columnas dinámicamente
        with open(ruta_csv, "r", encoding="utf-8-sig") as f:
            reader = csv.reader(f)
            headers = next(reader)
            columnas_str = ", ".join(headers)

            f.seek(0)  # Volver al inicio del archivo

            query_copy = f"""
                COPY {esquema}.{tabla} ({columnas_str})
                FROM STDIN 
                WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
            """
            cursor.copy_expert(query_copy, f)

        # 4. Sincronizar secuencias
        cursor.execute(
            f"""
            DO $$
            DECLARE
                v_col TEXT;
                v_seq TEXT;
                v_max BIGINT;
            BEGIN
                SELECT column_name INTO v_col
                FROM information_schema.columns
                WHERE table_schema = '{esquema}' 
                  AND table_name = '{tabla}' 
                  AND is_identity = 'YES'
                LIMIT 1;

                IF v_col IS NOT NULL THEN
                    v_seq := pg_get_serial_sequence('{esquema}.{tabla}', v_col);
                    IF v_seq IS NOT NULL THEN
                        EXECUTE 'SELECT COALESCE(MAX(' || quote_ident(v_col) || '), 1) FROM {esquema}.{tabla}' INTO v_max;
                        PERFORM setval(v_seq, v_max);
                    END IF;
                END IF;
            END $$;
        """
        )

        print(f"  └─  {esquema}.{tabla} cargada exitosamente.")

    conn.commit()
    cursor.close()
    conn.close()

    print("\n==================================================")
    print("¡IMPORTACIÓN COMPLETADA EXITOSAMENTE DESDE PYTHON!")
    print("==================================================")


if __name__ == "__main__":
    importar_datos()